GRANT CONNECT ON DATABASE lydia TO lydia_app;
GRANT USAGE ON SCHEMA public TO lydia_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO lydia_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO lydia_app;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO lydia_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO lydia_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO lydia_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO lydia_app;
